{% set python_min = '3.10' %}
{% set name = "finlogic" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/FinLogic-{{ version }}.tar.gz
  sha256: 023f1acf4e850d4eeed7154a84e43555808a52331e6169e021c014ac56b3d634

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-pep517 >=1.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.4.0
    - requests >=2.27.0
    - zstandard >=0.17.0

test:
  imports:
    - finlogic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Finance toolkit for listed Brazilian companies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CRCJ
